#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# border
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff5d2c63
yabai -m config normal_window_border_color   0xff555555

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# float window
yabai -m config window_topmost               off
yabai -m config window_shadow                off

# Space Labeling
yabai -m config --space 1 layout float

# Coding
yabai -m rule --add app="^iTerm2"     space=^4 || yabai -m rule --add app="^iTerm2"     space=^3
yabai -m rule --add app="^Emacs"      space=^4 || yabai -m rule --add app="^Emacs"      space=^3
yabai -m rule --add app="^Firefox"    space=^4 || yabai -m rule --add app="^Firefox"    space=^4
yabai -m rule --add app="^Mail"       space=^1

# Unmanaged
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^WeChat$"             manage=off
yabai -m rule --add app="^YoudaoDict"          manage=off

# Refresh
yabai -m signal --add event=display_removed action="launchctl kickstart -k \"gui/${UID}/homebrew.mxcl.yabai\""
yabai -m signal --add event=display_added   action="launchctl kickstart -k \"gui/${UID}/homebrew.mxcl.yabai\""

echo "yabai configuration loaded.."
